import { desc, eq } from "drizzle-orm";
import { db } from "../../db/index.js";
import { appointmentRequests, medicineRecords } from "../../db/schema.js";
import { hasValidSession } from "../lib/admin-auth.js";

function escapeHtml(value: unknown) {
  return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] || character);
}

function displayDate(value: unknown) {
  const date = new Date(String(value));
  return Number.isNaN(date.getTime()) ? String(value ?? "") : date.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" });
}

export default async (request: Request) => {
  if (!hasValidSession(request)) return new Response(null, { status: 303, headers: { Location: "/admin" } });
  const url = new URL(request.url);
  const id = Number(url.searchParams.get("id"));
  if (!Number.isInteger(id) || id < 1) return new Response("Invalid patient profile", { status: 400 });
  const [patient] = await db.select().from(appointmentRequests).where(eq(appointmentRequests.id, id)).limit(1);
  if (!patient) return new Response("Patient profile not found", { status: 404 });
  const medicines = await db.select().from(medicineRecords).where(eq(medicineRecords.appointmentId, id)).orderBy(desc(medicineRecords.id));
  const notice = url.searchParams.get("notice");
  const noticeHtml = notice === "medicine-saved" ? '<p class="notice">Medicine details saved successfully.</p>' : notice === "file-too-large" ? '<p class="notice error">Attachment is too large. Maximum size is 2 MB.</p>' : notice === "file-type" ? '<p class="notice error">Only PDF, JPG and PNG attachments are allowed.</p>' : "";
  const history = medicines.map((item) => `<article class="medicine"><div class="medicine-head"><div><small>Medicine / supplement</small><h3>${escapeHtml(item.medicineName)}</h3></div><time>${escapeHtml(displayDate(item.createdAt))}</time></div><dl><div><dt>Dosage</dt><dd>${escapeHtml(item.dosage) || "—"}</dd></div><div><dt>Frequency</dt><dd>${escapeHtml(item.frequency) || "—"}</dd></div><div><dt>Duration</dt><dd>${escapeHtml(item.duration) || "—"}</dd></div></dl>${item.instructions ? `<div class="instructions"><small>Instructions / notes</small><p>${escapeHtml(item.instructions)}</p></div>` : ""}${item.attachmentData ? `<a class="file" href="/admin/patient/file?id=${item.id}">View attachment · ${escapeHtml(item.attachmentName)}</a>` : ""}</article>`).join("");

  return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(patient.fullName)} · Patient profile</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:#173b36;font:15px/1.55 Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:32px 24px 70px}a{color:#173b36}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:24px}.back{display:inline-block;padding:11px 15px;border:1px solid #b9c9d3;border-radius:7px;text-decoration:none;font-weight:700}.eyebrow,small,label,dt{font-size:11px;font-weight:700;letter-spacing:1.05px;text-transform:uppercase;color:#6c7f8c}.eyebrow{color:#315f8f}h1{font:600 clamp(34px,5vw,52px) Georgia,serif;margin:6px 0}.subtitle{margin:0;color:#687a72}.panel{background:white;border:1px solid #d6e0e6;border-radius:14px;padding:24px;box-shadow:0 4px 15px #173b360c}.patient-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:22px}.patient-grid strong{display:block;margin-top:5px}.concern{margin-top:20px;padding:16px;border-radius:8px;background:#f4f7f9}.concern p,.instructions p{white-space:pre-wrap;margin:6px 0 0}.layout{display:grid;grid-template-columns:.85fr 1.15fr;gap:20px;margin-top:20px}.panel h2{font:600 28px Georgia,serif;margin:0 0 6px}.helper{margin:0 0 20px;color:#66766e;font-size:13px}.notice{padding:12px 15px;border-radius:8px;background:#e8f4e9;color:#245c35;font-weight:700}.notice.error{background:#fff0ec;color:#a24432}label{display:block;margin-top:14px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}input,textarea{display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #b8c8d2;border-radius:7px;background:#fff;font:14px Arial,sans-serif;color:#173b36;text-transform:none}textarea{resize:vertical}button{width:100%;margin-top:18px;padding:13px 16px;border:0;border-radius:7px;background:#315f8f;color:white;font-weight:700;cursor:pointer}.privacy{font-size:11px;color:#718079;margin:12px 0 0}.history{display:grid;gap:12px}.medicine{border:1px solid #dbe4e9;border-radius:10px;padding:18px}.medicine-head{display:flex;justify-content:space-between;gap:18px}.medicine h3{font:600 22px Georgia,serif;margin:3px 0}.medicine time{font-size:12px;color:#6f7f78}.medicine dl{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0 0}.medicine dl div{background:#f4f7f9;padding:10px;border-radius:7px}.medicine dd{margin:4px 0 0;font-weight:700}.instructions{margin-top:13px}.file{display:inline-block;margin-top:14px;padding:8px 11px;border-radius:6px;background:#e8f1f9;color:#245b8c;text-decoration:none;font-weight:700;font-size:13px}.empty{padding:24px;border:1px dashed #b8c8d2;border-radius:9px;text-align:center;color:#66766e}@media(max-width:800px){.patient-grid{grid-template-columns:1fr 1fr}.layout{grid-template-columns:1fr}}@media(max-width:520px){.wrap{padding:22px 14px 50px}.top{align-items:start;flex-direction:column}.patient-grid,.two,.medicine dl{grid-template-columns:1fr}.medicine-head{flex-direction:column;gap:4px}}
</style></head><body><main class="wrap"><div class="top"><div><p class="eyebrow">Patient profile · Request #${patient.id}</p><h1>${escapeHtml(patient.fullName)}</h1><p class="subtitle">${escapeHtml(patient.age)} years · ${escapeHtml(patient.city)}</p></div><a class="back" href="/admin#appointment-${patient.id}">← Back to dashboard</a></div>${noticeHtml}<section class="panel"><div class="patient-grid"><div><small>Mobile</small><strong><a href="tel:${escapeHtml(patient.mobileNumber)}">${escapeHtml(patient.mobileNumber)}</a></strong></div><div><small>Preferred date</small><strong>${escapeHtml(patient.preferredDate)}</strong></div><div><small>Preferred time</small><strong>${escapeHtml(patient.preferredTime)}</strong></div><div><small>Status</small><strong>${escapeHtml(patient.status)}</strong></div></div><div class="concern"><small>Health concern or course enquiry</small><p>${escapeHtml(patient.healthConcern)}</p></div></section><div class="layout"><section class="panel"><h2>Add medicine details</h2><p class="helper">Save an internal medicine or supplement record for this patient.</p><form method="POST" action="/admin/patient/medicine" enctype="multipart/form-data"><input type="hidden" name="appointment-id" value="${patient.id}"><label>Medicine or supplement name *<input name="medicine-name" required maxlength="200" placeholder="e.g. Medicine name"></label><div class="two"><label>Dosage<input name="dosage" maxlength="120" placeholder="e.g. 1 tablet"></label><label>Frequency<input name="frequency" maxlength="120" placeholder="e.g. Twice daily"></label></div><label>Duration<input name="duration" maxlength="120" placeholder="e.g. 7 days"></label><label>Instructions / notes<textarea name="instructions" rows="4" maxlength="4000" placeholder="Timing, precautions or other details"></textarea></label><label>Prescription attachment<input name="attachment" type="file" accept="image/jpeg,image/png,application/pdf"></label><button type="submit">Save medicine details</button><p class="privacy">Private admin record. Maximum attachment size: 2 MB. Verify all medicine details before use; this record does not create or replace a medical prescription.</p></form></section><section class="panel"><h2>Medicine history</h2><p class="helper">${medicines.length} saved ${medicines.length === 1 ? "record" : "records"}</p><div class="history">${history || '<p class="empty">No medicine details have been added yet.</p>'}</div></section></div></main></body></html>`, { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });
};

export const config = { path: "/admin/patient" };
